#!/bin/bash

docker run -ti --rm \
           -e DISPLAY \
           -v $HOME/.Xauthority:/home/developer/.Xauthority \
           -v "`pwd`":/workspace \
           --net=host fgrehm/eclipse:v4.4.1
